# Generated by Django 5.1.4 on 2026-04-29 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_playeralias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('match', 'Partido'), ('training', 'Entrenamiento'), ('medical_checkup', 'Chequeo médico'), ('physical_test', 'Test físico'), ('team_speech', 'Charla / reunión'), ('nutrition', 'Nutricional'), ('other', 'Otro')], max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('scope', models.CharField(choices=[('individual', 'Individual'), ('category', 'Categoría completa'), ('custom', 'Personalizado')], default='individual', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Reserved for type-specific fields (e.g. opponent for matches).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Set when the event was created for an entire category. Informational — participants are still listed explicitly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.department')),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='core.player')),
            ],
            options={
                'ordering': ('-starts_at',),
                'indexes': [models.Index(fields=['club', 'starts_at'], name='events_even_club_id_90c853_idx'), models.Index(fields=['department', 'starts_at'], name='events_even_departm_e6ddcc_idx')],
            },
        ),
    ]
