# Generated by Django 5.1.4 on 2026-05-18 — hand-edited to use
# SeparateDatabaseAndState because Django can't add `through=` to an
# existing M2M via AlterField. The existing `events_event_participants`
# auto-created M2M table is empty (verified pre-migration) so we drop
# it; the new `EventParticipant` through-model owns the relationship
# from here on.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contract_legacy_raw_player_legacy_raw_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='legacy_raw',
            field=models.JSONField(
                blank=True, default=dict,
                help_text='Source row(s) from a legacy system this event was migrated from.',
            ),
        ),
        # 1) Create the new through model. Django creates a fresh table
        #    `events_eventparticipant`. The OLD auto-table
        #    `events_event_participants` is still there, untouched.
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance', models.CharField(
                    choices=[('scheduled', 'Programado'), ('attended', 'Asistió'), ('missed', 'No asistió'), ('excused', 'Justificado')],
                    db_index=True, default='scheduled', max_length=12,
                )),
                ('absence_reason', models.CharField(
                    blank=True,
                    help_text="Why the player didn't attend. Only applies when attendance is 'missed' or 'excused'.",
                    max_length=200,
                )),
                ('post_event_notes', models.TextField(
                    blank=True,
                    help_text='Staff observations after the event — treatment given, follow-up needed, etc.',
                )),
                ('match_role', models.CharField(
                    blank=True,
                    choices=[
                        ('titular', 'Titular'), ('suplente_ingresa', 'Suplente — ingresa'),
                        ('suplente_no_ingresa', 'Suplente — no ingresa'),
                        ('no_citado', 'No citado'), ('lesionado', 'Lesionado'),
                        ('suspendido', 'Suspendido'), ('seleccion', 'Selección'),
                        ('promovido', 'Promovido'), ('citado_no_vestir', 'Citado sin vestir'),
                    ],
                    db_index=True,
                    help_text="Citation status. Only set when event.event_type='match'.",
                    max_length=24, null=True,
                )),
                ('minutes_played', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('external_id', models.IntegerField(
                    blank=True, db_index=True,
                    help_text='Legacy citaciones.id_citaciones for migration idempotency.',
                    null=True,
                )),
                ('legacy_raw', models.JSONField(
                    blank=True, default=dict,
                    help_text='Source row(s) from a legacy system this row was migrated from.',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='event_participants', to='events.event',
                )),
                ('player', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='event_participations', to='core.player',
                )),
                ('position_played', models.ForeignKey(
                    blank=True,
                    help_text='Position actually played in this match (may differ from Player.position for utility players).',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='event_participations', to='core.position',
                )),
            ],
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['player', 'match_role'], name='events_even_player__8daaff_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'attendance'], name='events_even_event_i_db8bce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'player')},
        ),
        # 2) Now flip the M2M to use `through=EventParticipant`.
        #    Django's SchemaEditor refuses to do this via `AlterField`
        #    because the through= toggle is unsupported. We split the
        #    operation: the Django STATE learns about the through model,
        #    while the DATABASE just drops the old empty auto-M2M table
        #    (verified empty on 2026-05-18 before applying).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='event',
                    name='participants',
                    field=models.ManyToManyField(
                        blank=True, related_name='events',
                        through='events.EventParticipant', to='core.player',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS events_event_participants',
                    reverse_sql=(
                        # On rollback we recreate the empty auto-M2M table.
                        'CREATE TABLE IF NOT EXISTS events_event_participants ('
                        '  id BIGSERIAL PRIMARY KEY,'
                        '  event_id UUID NOT NULL REFERENCES events_event(id) DEFERRABLE INITIALLY DEFERRED,'
                        '  player_id UUID NOT NULL REFERENCES core_player(id) DEFERRABLE INITIALLY DEFERRED,'
                        '  UNIQUE (event_id, player_id)'
                        ')'
                    ),
                ),
            ],
        ),
    ]
