# Generated by Django 5.1.4 on 2026-06-19 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_legacy_raw_eventparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='api_football', max_length=32)),
                ('fixture_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('lineups', models.JSONField(blank=True, default=list)),
                ('events', models.JSONField(blank=True, default=list)),
                ('team_statistics', models.JSONField(blank=True, default=list)),
                ('player_statistics', models.JSONField(blank=True, default=list)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_data', to='events.event')),
            ],
        ),
    ]
