# Generated by Django 5.1.4 on 2026-06-19 00:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('events', '0003_matchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentScouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.BigIntegerField(help_text='API-Football team id of the opponent.')),
                ('team_name', models.CharField(max_length=140)),
                ('season', models.IntegerField()),
                ('source', models.CharField(default='api_football', max_length=32)),
                ('recent_form', models.JSONField(blank=True, default=list)),
                ('last_lineup', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(help_text='The club doing the scouting (data scoping), not the opponent.', on_delete=django.db.models.deletion.CASCADE, related_name='opponent_scouting', to='core.club')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'team_id', 'season'], name='events_oppo_club_id_1bf87d_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'team_id', 'season'), name='uniq_opponent_scouting')],
            },
        ),
    ]
