# Generated by Django 5.1.4 on 2026-06-30 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_opponentscouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='api_football', max_length=32)),
                ('external_id', models.IntegerField(help_text='Provider team id (e.g. API-Football).')),
                ('name', models.CharField(max_length=140)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_id'], name='events_exte_provide_b2d7f0_idx'), models.Index(fields=['name'], name='events_exte_name_16623b_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_external_team')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='opponent_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='events.externalteam'),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='api_football', max_length=32)),
                ('external_id', models.IntegerField(help_text='Provider league id.')),
                ('season', models.IntegerField()),
                ('name', models.CharField(max_length=140)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='competitions', to='events.externalteam')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'external_id', 'season'], name='events_comp_provide_d4bbea_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id', 'season'), name='uniq_competition_season')],
            },
        ),
    ]
