# Generated by Django 5.1.4 on 2026-08-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_externalteam_event_opponent_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='head_to_head',
            field=models.JSONField(blank=True, default=list, help_text='Recent meetings between the two teams (COMET /h2h).'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='standings',
            field=models.JSONField(blank=True, default=list, help_text='Official competition table as of this match (COMET /standings).'),
        ),
    ]
