# Generated by Django 5.1.4 on 2026-08-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bracket_category_cohort_year_playerteammembership_and_more'),
        ('events', '0006_matchdata_head_to_head_matchdata_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bracket',
            field=models.ForeignKey(blank=True, help_text='For matches: the competition age group the fixture belongs to (Sub 15, Primera). Distinct from `category` on purpose — a Sub 18 fixture is played by TWO cohort teams at once (the 2009s and the 2008s), so a single team FK cannot describe who turned out. `category` stays as the principal team; this says which competition it was.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.bracket'),
        ),
    ]
