# Generated by Django 5.1.4 on 2026-04-27 04:39

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('medical', 'Medical'), ('physical', 'Physical'), ('nutritional', 'Nutritional'), ('psychosocial', 'Psychosocial'), ('technical', 'Technical')], max_length=32)),
                ('config_schema', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False, help_text='Once results exist, the template is locked. New changes spawn a new version.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(related_name='exam_templates', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.player')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='exams.examtemplate')),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=django.contrib.postgres.indexes.GinIndex(fields=['config_schema'], name='exams_examt_config__a3c7f3_gin'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=django.contrib.postgres.indexes.GinIndex(fields=['result_data'], name='exams_examr_result__16d890_gin'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['player', 'recorded_at'], name='exams_examr_player__1df13f_idx'),
        ),
    ]
