# Generated by Django 5.1.4 on 2026-04-27 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_category_departments'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_templates', to='core.department'),
        ),
    ]
