# Generated by Django 5.1.4 on 2026-04-29 02:23

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examtemplate_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='input_config',
            field=models.JSONField(default=exams.models.default_input_config, help_text='Controls how staff submit data for this template. See model docstring for the schema.'),
        ),
    ]
