# Generated by Django 5.1.4 on 2026-04-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playeralias'),
        ('events', '0001_initial'),
        ('exams', '0003_examtemplate_input_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional link to a calendar event (e.g. the match this GPS export came from).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to='events.event'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['event'], name='exams_examr_event_i_1cebfc_idx'),
        ),
    ]
