# Generated by Django 5.1.4 on 2026-04-29 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examresult_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Determina el orden en el formulario y el reporte.')),
                ('key', models.CharField(help_text='Identificador interno (slug). Solo letras, números y guión bajo. Una vez que el template tiene resultados, no debería cambiar.', max_length=64)),
                ('label', models.CharField(help_text='Etiqueta visible para el staff.', max_length=140)),
                ('type', models.CharField(choices=[('number', 'Número'), ('text', 'Texto'), ('categorical', 'Categórico (lista)'), ('calculated', 'Calculado (fórmula)'), ('boolean', 'Sí/No'), ('date', 'Fecha')], default='number', max_length=16)),
                ('unit', models.CharField(blank=True, help_text='Ej. kg, cm, min, m/min.', max_length=24)),
                ('group', models.CharField(blank=True, help_text="Sección lógica en el formulario (ej. 'Datos básicos', 'Distancia').", max_length=80)),
                ('options', models.JSONField(blank=True, default=list, help_text='Solo para tipo categórico. Lista de strings, una opción por elemento.')),
                ('formula', models.TextField(blank=True, help_text='Solo para tipo calculado. Ej. [peso] / (([talla] / 100) ** 2).')),
                ('chart_type', models.CharField(blank=True, choices=[('', 'Ninguno'), ('line', 'Línea'), ('stat_card', 'Tarjeta de estadística'), ('body_map', 'Mapa corporal')], default='', help_text='Visualización por defecto para este campo en las tarjetas de resumen.', max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('multiline', models.BooleanField(default=False, help_text='Solo para texto. Renderiza un cuadro de texto multi-línea.')),
                ('rows', models.PositiveSmallIntegerField(blank=True, help_text='Solo para texto multi-línea. Cantidad de filas visibles.', null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='exams.examtemplate')),
            ],
            options={
                'ordering': ('sort_order', 'key'),
                'unique_together': {('template', 'key')},
            },
        ),
    ]
