# Generated by Django 5.1.4 on 2026-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_backfill_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='link_to_match',
            field=models.BooleanField(default=False, help_text="When enabled, the data-entry form shows an 'Asociar partido' selector. The picked match becomes the authoritative timestamp (overrides recorded_at) and is FK-stored on every result. Applies to single, bulk-ingest, and team-table forms."),
        ),
    ]
