# Generated by Django 5.1.4 on 2026-04-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_backfill_link_to_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('number', 'Número'), ('text', 'Texto'), ('categorical', 'Categórico (lista)'), ('calculated', 'Calculado (fórmula)'), ('boolean', 'Sí/No'), ('date', 'Fecha'), ('file', 'Archivo (uno o varios)')], default='number', max_length=16),
        ),
    ]
