# Generated by Django 5.1.4 on 2026-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_templatefield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='writes_to_player_field',
            field=models.CharField(blank=True, choices=[('', '—'), ('current_weight_kg', 'Player.current_weight_kg'), ('current_height_cm', 'Player.current_height_cm'), ('sex', 'Player.sex')], default='', help_text='Cuando se guarda un resultado, se copia el valor de este campo al atributo del jugador (sólo si es el resultado más reciente para esta plantilla).', max_length=32),
        ),
    ]
