# Generated by Django 5.1.4 on 2026-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_current_height_cm_player_current_weight_kg'),
        ('exams', '0010_templatefield_writes_to_player_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="Identificador estable usado en fórmulas para referenciar resultados de esta plantilla, ej. `[pentacompartimental.peso]`. Se autogenera del nombre si se deja en blanco. No puede ser 'player'.", max_length=80),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['slug'], name='exams_examt_slug_5b2265_idx'),
        ),
    ]
