# Generated by Django 5.1.4 on 2026-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_backfill_examtemplate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='inputs_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
