# Generated by Django 5.1.4 on 2026-05-01 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_player_status'),
        ('events', '0001_initial'),
        ('exams', '0013_examresult_inputs_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='episode_config',
            field=models.JSONField(blank=True, default=dict, help_text='Episodic-template config. Required when is_episodic=True. Shape: {"stage_field": "stage", "open_stages": ["injured", "recovery", "reintegration"], "closed_stage": "closed", "title_template": "{type} — {body_part}"}. open_stages is ordered WORST → BEST.'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='is_episodic',
            field=models.BooleanField(default=False, help_text="When enabled, results on this template form linked Episodes. Each result either opens a new Episode or progresses an existing open one (via episode_id). The Episode auto-derives stage / status / title from the latest linked result, and the player's Player.status is recomputed from their open episodes."),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=8)),
                ('stage', models.CharField(blank=True, help_text="Free-form per template; populated by signal from latest result's stage_field.", max_length=40)),
                ('title', models.CharField(blank=True, help_text='Human-readable summary (auto-derived from latest result via title_template).', max_length=200)),
                ('started_at', models.DateTimeField(help_text='When the first linked result was recorded.')),
                ('ended_at', models.DateTimeField(blank=True, help_text="Set when the episode transitions to 'closed' (= recorded_at of the closing result).", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_episodes', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.player')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='exams.examtemplate')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='examresult',
            name='episode',
            field=models.ForeignKey(blank=True, help_text="Set when the result is part of an episodic template's lifecycle. PROTECT prevents accidental episode deletion while results exist.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='exams.episode'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['episode'], name='exams_examr_episode_69e371_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['player', 'status'], name='exams_episo_player__1ee384_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['template', 'status'], name='exams_episo_templat_eec76a_idx'),
        ),
    ]
