# Generated by Django 5.1.4 on 2026-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examtemplate_episode_config_examtemplate_is_episodic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='option_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Solo para tipo categórico. Diccionario opcional que asocia cada valor de `options` con la etiqueta visible en el formulario (ej. {"injured": "Lesionado"}). Si está vacío o falta una clave, se muestra el valor tal cual.'),
        ),
    ]
