# Generated by Django 5.1.4 on 2026-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_templatefield_option_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='show_injuries',
            field=models.BooleanField(default=False, help_text="When enabled, the data-entry form for this template displays a panel listing the player's open injuries, with a button to add a new one without leaving the form. Useful for daily-notes / session-tracking templates where the doctor needs context on current injuries while filling unrelated data."),
        ),
    ]
