# Generated by Django 5.1.4 on 2026-05-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_examtemplate_show_injuries'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='option_regions',
            field=models.JSONField(blank=True, default=dict, help_text='Solo para tipo categórico. Diccionario opcional que asocia cada valor de `options` con una región del cuerpo (head, neck, chest, abdomen, pelvis, left_shoulder, right_shoulder, left_arm, right_arm, left_forearm, right_forearm, left_hand, right_hand, left_thigh, right_thigh, left_knee, right_knee, left_calf, right_calf, left_foot, right_foot). Lo usa el widget `body_map_heatmap` para colorear regiones según cuántos resultados las mencionan.'),
        ),
    ]
