# Generated by Django 5.1.4 on 2026-05-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_examtemplate_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='direction_of_good',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutro (sin opinión)'), ('up', 'Más es mejor (verde si sube)'), ('down', 'Menos es mejor (verde si baja)')], default='neutral', help_text="Para campos numéricos/calculados. Define cómo colorear los deltas de variación en widgets como Roster Matrix: 'up' pinta verde un alza y rojo una baja; 'down' invierte; 'neutral' mantiene el paleta azul/naranja sin juicio.", max_length=10),
        ),
    ]
