# Generated by Django 5.1.4 on 2026-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_templatefield_direction_of_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='reference_ranges',
            field=models.JSONField(blank=True, default=list, help_text='Bandas de referencia clínica para campos numéricos. Lista de objetos: {"label": "Normal", "min": 30, "max": 200, "color": "#16a34a"}. min y max son opcionales por banda (banda abierta a un lado), pero al menos uno debe estar. Las bandas deben ser disjuntas y ordenadas de menor a mayor. Ejemplo CK: [{"label":"Bajo","max":30},{"label":"Normal","min":30,"max":200},{"label":"Elevado","min":200,"max":400},{"label":"Severo","min":400}]'),
        ),
    ]
