# Generated by Django 5.1.4 on 2026-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_templatefield_reference_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='legacy_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Source row(s) from a legacy system this episode was migrated from.'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='legacy_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Source row(s) from a legacy system this result was migrated from. Populated by `manage.py migrate_legacy_data`; empty for native rows.'),
        ),
    ]
