# Generated by Django 5.1.4 on 2026-07-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_episode_legacy_raw_examresult_legacy_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='available_at',
            field=models.DateTimeField(blank=True, help_text="Date the player became available to be selected ('disponible para ser citado') — independent of episode closure. A player can be available (RTP) while the episode stays open for monitoring; closing time-loss (ended_at) is a separate event. Set via PATCH /episodes/{id}.", null=True),
        ),
    ]
