# Generated by Django 5.1.4 on 2026-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_episodenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodenote',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
