# Generated by Django 5.1.4 on 2026-07-16 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kinedailyentry'),
        ('exams', '0024_episodenote_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValdIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='When off, the club is skipped by the scheduled VALD sync.')),
                ('region', models.CharField(choices=[('use', 'US East (use)'), ('euw', 'Europe West (euw)'), ('aue', 'Australia East (aue)')], default='use', help_text='VALD data region for this tenant (determined by VALD).', max_length=8)),
                ('tenant_id', models.CharField(help_text='VALD tenantId (GUID) from the Tenants API.', max_length=64)),
                ('client_id', models.CharField(blank=True, help_text='Per-club OAuth client_id. Blank → uses settings.VALD_CLIENT_ID.', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='Per-club OAuth client_secret. Blank → uses settings.VALD_CLIENT_SECRET. Stored as-is; treat as a secret.', max_length=255)),
                ('sync_cursors', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vald_integration', to='core.club')),
            ],
            options={
                'verbose_name': 'VALD integration',
                'verbose_name_plural': 'VALD integrations',
            },
        ),
        migrations.CreateModel(
            name='ValdProfileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vald_profile_id', models.CharField(max_length=64)),
                ('given_name', models.CharField(blank=True, max_length=120)),
                ('family_name', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('sync_id', models.CharField(blank=True, max_length=128)),
                ('match_method', models.CharField(choices=[('external_id', 'externalId'), ('name_dob', 'nombre + fecha nac.'), ('name', 'nombre'), ('manual', 'manual'), ('unresolved', 'sin resolver')], default='unresolved', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vald_profile_links', to='core.club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vald_links', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'match_method'], name='exams_valdp_club_id_76040d_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'vald_profile_id'), name='uniq_vald_profile_per_club')],
            },
        ),
    ]
