# Generated by Django 5.1.4 on 2026-07-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_valdintegration_valdprofilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='valdintegration',
            name='cmj_template_slug',
            field=models.CharField(blank=True, help_text="Slug de plantilla destino para CMJ. Vacío → 'cmj'.", max_length=80),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='hip_adab_template_slug',
            field=models.CharField(blank=True, help_text="Slug de plantilla destino para Hip AD/AB. Vacío → 'hip_adab'.", max_length=80),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='imtp_template_slug',
            field=models.CharField(blank=True, help_text="Slug de plantilla destino para IMTP. Vacío → 'imtp'.", max_length=80),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='nordico_template_slug',
            field=models.CharField(blank=True, help_text="Slug de plantilla destino para Nordic. Vacío → 'nordico'.", max_length=80),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='sync_forcedecks',
            field=models.BooleanField(default=True, help_text='Ingerir tests de ForceDecks (CMJ / IMTP).'),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='sync_forceframe',
            field=models.BooleanField(default=True, help_text='Ingerir tests de ForceFrame (Hip AD/AB).'),
        ),
        migrations.AddField(
            model_name='valdintegration',
            name='sync_nordbord',
            field=models.BooleanField(default=True, help_text='Ingerir tests de NordBord (Nordic).'),
        ),
    ]
