# Generated by Django 5.1.4 on 2026-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_valdintegration_cmj_template_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('number', 'Número'), ('text', 'Texto'), ('categorical', 'Categórico (lista)'), ('calculated', 'Calculado (fórmula)'), ('boolean', 'Sí/No'), ('date', 'Fecha'), ('file', 'Archivo (uno o varios)'), ('bodymap', 'Mapa corporal (zonas + pin)')], default='number', max_length=16),
        ),
    ]
