# Generated by Django 5.1.4 on 2026-08-13 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_playercallup'),
        ('exams', '0027_alter_templatefield_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatapultAthleteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_id', models.CharField(help_text='UUID del atleta en Catapult.', max_length=64, unique=True)),
                ('athlete_name', models.CharField(blank=True, help_text='Nombre en Catapult (referencia).', max_length=200)),
                ('match_method', models.CharField(choices=[('external_id', 'external id'), ('name_dob', 'name + DOB'), ('name', 'name'), ('manual', 'manual')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catapult_links', to='core.player')),
            ],
            options={
                'verbose_name': 'Vínculo atleta Catapult',
                'verbose_name_plural': 'Vínculos atleta Catapult',
            },
        ),
        migrations.CreateModel(
            name='CatapultIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Con esto apagado, la categoría se omite en la sincronización horaria.')),
                ('base_url', models.CharField(default='https://backend-us.openfield.catapultsports.com/api/v6', max_length=200)),
                ('api_token', models.TextField(help_text='Bearer JWT del tenant Catapult (por equipo).')),
                ('catapult_team_id', models.CharField(help_text='UUID del equipo en Catapult que corresponde a esta categoría.', max_length=64)),
                ('classify_strategy', models.CharField(choices=[('fixture', 'Partido si hay fixture ese día (recomendado)'), ('tag', 'Por tag de Catapult (Activity / DayCode)'), ('name', "Por nombre de la actividad (' vs ')"), ('hybrid', 'Fixture y, si no hay, tag / nombre')], default='fixture', help_text='Cómo decidir partido vs entrenamiento.', max_length=12)),
                ('sync_matches', models.BooleanField(default=True, help_text='Ingerir partidos (→ gps_partido).')),
                ('sync_training', models.BooleanField(default=True, help_text='Ingerir entrenamientos (→ gps_sesion).')),
                ('min_training_minutes', models.PositiveIntegerField(default=0, help_text='Omitir entrenamientos más cortos que esto (limpieza de datos).')),
                ('partido_template_slug', models.CharField(default='gps_partido', max_length=64)),
                ('sesion_template_slug', models.CharField(default='gps_sesion', max_length=64)),
                ('lookback_days', models.PositiveIntegerField(default=14, help_text='Cuántos días hacia atrás revisa cada corrida.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catapult_integration', to='core.category')),
            ],
            options={
                'verbose_name': 'Integración Catapult',
                'verbose_name_plural': 'Integraciones Catapult',
            },
        ),
    ]
