# Generated by Django 5.1.4 on 2026-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_catapultathletelink_catapultintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catapultintegration',
            name='classify_strategy',
            field=models.CharField(choices=[('tag', "Por señal de Catapult: DayCode=MD o nombre ' vs ' (recomendado)"), ('fixture', 'Sólo si hay fixture en SLAB ese día exacto'), ('name', "Sólo por nombre de la actividad (' vs ')"), ('hybrid', 'Señal de Catapult y, si no, fixture del día')], default='tag', help_text='Cómo decidir partido vs entrenamiento.', max_length=12),
        ),
    ]
