# Generated by Django 5.1.4 on 2026-08-18 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_playercallup'),
        ('exams', '0029_alter_catapultintegration_classify_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CometIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Con esto apagado, el club se omite en la sincronización.')),
                ('base_url', models.CharField(default='https://api-latam.analyticom.de', max_length=200)),
                ('api_key', models.TextField(help_text='API_KEY entregada por la federación (va como header en cada llamada).')),
                ('tenant', models.CharField(default='ANFP', help_text="Tenant COMET, ej. 'ANFP' para Chile. Va en la ruta.", max_length=32)),
                ('comet_team_id', models.BigIntegerField(help_text='ID del club en COMET, ej. 40017 = Universidad de Chile.')),
                ('organization_id', models.BigIntegerField(help_text='ID de la organización / federación en COMET, ej. 39972 = ANFP.')),
                ('utc_offset', models.IntegerField(default=-4, help_text='Offset horario en HORAS que pide COMET para agrupar por día (Chile: -4). Sólo afecta el agrupamiento del proveedor: la hora real de cada partido se toma de `dateTimeUTC`, así que el horario de verano no la altera.')),
                ('lookback_days', models.PositiveIntegerField(default=30, help_text='Cuántos días hacia atrás revisa cada corrida.')),
                ('template_slug', models.CharField(default='ficha_partido', help_text='Plantilla que recibe la ficha por jugador.', max_length=64)),
                ('update_event_metadata', models.BooleanField(default=True, help_text='Escribir los datos generales del partido (marcador, fecha del torneo, árbitro, estadio) en el Event.')),
                ('store_raw_match_data', models.BooleanField(default=True, help_text='Guardar alineaciones y eventos crudos en MatchData (auditoría).')),
                ('create_missing_events', models.BooleanField(default=False, help_text='Crear el Event del partido si no existe ninguno en SLAB. Apagado por defecto: así la sincronización sólo enriquece partidos ya cargados y no inventa calendario.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comet_integration', to='core.club')),
            ],
            options={
                'verbose_name': 'Integración COMET',
                'verbose_name_plural': 'Integraciones COMET',
            },
        ),
        migrations.CreateModel(
            name='CometCompetitionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition_id', models.BigIntegerField(help_text='ID de la competencia en COMET.')),
                ('competition_name', models.CharField(blank=True, max_length=200)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('ignored', models.BooleanField(default=False, help_text='Marcar para omitir esta competencia sin que aparezca como pendiente.')),
                ('auto_resolved', models.BooleanField(default=False, help_text='La categoría la dedujo la sincronización (no un humano).')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Vacío = sin resolver: los partidos de esta competencia se omiten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comet_competition_links', to='core.category')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_links', to='exams.cometintegration')),
            ],
            options={
                'verbose_name': 'Competencia COMET',
                'verbose_name_plural': 'Competencias COMET',
                'constraints': [models.UniqueConstraint(fields=('integration', 'competition_id'), name='uniq_comet_competition_per_integration')],
            },
        ),
        migrations.CreateModel(
            name='CometPlayerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_id', models.BigIntegerField(help_text='personId estable en COMET.')),
                ('fifa_id', models.CharField(blank=True, max_length=32)),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_method', models.CharField(choices=[('name_dob', 'nombre + fecha nac.'), ('name', 'nombre'), ('manual', 'manual'), ('unresolved', 'sin resolver')], default='unresolved', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_links', to='exams.cometintegration')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comet_links', to='core.player')),
            ],
            options={
                'verbose_name': 'Vínculo jugador COMET',
                'verbose_name_plural': 'Vínculos jugador COMET',
                'constraints': [models.UniqueConstraint(fields=('integration', 'person_id'), name='uniq_comet_person_per_integration')],
            },
        ),
    ]
