# Generated by Django 5.1.4 on 2026-04-30 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_playeralias'),
        ('exams', '0008_backfill_link_to_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('goal', 'Objetivo'), ('threshold', 'Umbral')], max_length=20)),
                ('source_id', models.UUIDField(help_text='UUID of the source row (Goal.id, Threshold.id, …).')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('dismissed', 'Descartada'), ('resolved', 'Resuelta')], default='active', max_length=10)),
                ('message', models.TextField()),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.player')),
            ],
            options={
                'ordering': ('-fired_at',),
                'indexes': [models.Index(fields=['player', 'status'], name='goals_alert_player__616c3b_idx'), models.Index(fields=['source_type', 'source_id'], name='goals_alert_source__297a47_idx')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text="The key from template.config_schema['fields'][].key to evaluate.", max_length=80)),
                ('operator', models.CharField(choices=[('<=', '≤'), ('<', '<'), ('==', '='), ('>=', '≥'), ('>', '>')], max_length=2)),
                ('target_value', models.FloatField()),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('met', 'Cumplido'), ('missed', 'No cumplido'), ('cancelled', 'Cancelado')], default='active', max_length=12)),
                ('last_value', models.FloatField(blank=True, help_text="The player's value at the last evaluation. Null if no reading existed.", null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.player')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='exams.examtemplate')),
            ],
            options={
                'ordering': ('-due_date', '-created_at'),
                'indexes': [models.Index(fields=['status', 'due_date'], name='goals_goal_status_f567cb_idx'), models.Index(fields=['player', 'status'], name='goals_goal_player__31d383_idx')],
            },
        ),
    ]
