# Generated by Django 5.1.4 on 2026-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='Most-recent firing of the source rule. Equal to `fired_at` for single-fire alerts (goals); refreshed each time a threshold rule re-triggers while the alert is still active.', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times the source rule has triggered since this alert was raised. Resets to 1 when a new alert is created (after dismissal).'),
        ),
    ]
