# Generated by Django 5.1.4 on 2026-05-01 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_current_height_cm_player_current_weight_kg'),
        ('exams', '0013_examresult_inputs_snapshot'),
        ('goals', '0003_backfill_alert_last_fired_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text="Key from the template's config_schema fields. Must be numeric or calculated.", max_length=80)),
                ('kind', models.CharField(choices=[('bound', 'Límite (umbral fijo)'), ('variation', 'Variación (% vs. ventana)')], max_length=12)),
                ('config', models.JSONField(default=dict, help_text='bound: {"upper": float?, "lower": float?}. variation: {"window": {"kind":"last_n","n":int} or {"kind":"timedelta","days":int}, "threshold_pct": float, "direction": "any"|"increase"|"decrease"}')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('message_template', models.CharField(blank=True, help_text='Plantilla del mensaje. Placeholders: {value}, {field_label}, {upper}, {lower}, {baseline}, {pct_change}, {direction}, {window_desc}. Si está vacío, se autogenera.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Restrict to one category. Empty = applies to every category that uses this template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='exams.examtemplate')),
            ],
            options={
                'ordering': ('template__name', 'field_key', 'kind'),
                'indexes': [models.Index(fields=['template', 'is_active'], name='goals_alert_templat_217d01_idx')],
            },
        ),
    ]
