# Generated by Django 5.1.4 on 2026-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alertrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='config',
            field=models.JSONField(default=dict, help_text='bound: {"upper": float?, "lower": float?}. variation: {"window": {"kind":"last_n","n":int} or {"kind":"timedelta","days":int}, "threshold_pct": float?, "threshold_units": float?, "direction": "any"|"increase"|"decrease"} — at least one threshold required.'),
        ),
    ]
