# Generated by Django 5.1.4 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_alertrule_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='warn_days_before',
            field=models.PositiveIntegerField(blank=True, default=7, help_text="Fire a pre-deadline warning alert when due_date is within this many days AND the goal isn't currently met. Leave blank / 0 to disable warnings for this goal. Default: 7.", null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('threshold', 'Umbral')], max_length=20),
        ),
    ]
