# Generated by Django 5.1.4 on 2026-05-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_warn_days_before_alter_alert_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('threshold', 'Umbral'), ('medication', 'Medicación (WADA)')], max_length=20),
        ),
    ]
