# Generated by Django 5.1.4 on 2026-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_alertrule_config_alter_alertrule_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='bound: {"upper": float?, "lower": float?}. variation: {"window": {"kind":"last_n","n":int} or {"kind":"timedelta","days":int}, "threshold_pct": float?, "threshold_units": float?, "direction": "any"|"increase"|"decrease"} — at least one threshold required. band: {} (auto-detect alert band via color heuristic) or {"trigger_labels": ["Elevado", ...]} to fire on specific bands.'),
        ),
    ]
