# Generated by Django 5.1.4 on 2026-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_alertrule_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('threshold', 'Umbral'), ('medication', 'Medicación (WADA)'), ('training_load', 'Carga de entrenamiento')], max_length=20),
        ),
    ]
