# Generated by Django 5.1.4 on 2026-07-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_alter_alert_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source_recorded_at',
            field=models.DateTimeField(blank=True, help_text="recorded_at of the reading that fired this alert (the structured 'dato del …' date, not just embedded in the message). Null for goal-lifecycle alerts. Drives the freshness badge + GPS 72h sweep.", null=True),
        ),
    ]
