# Generated by Django 5.1.4 on 2026-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_alert_source_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text='Optional context filters (all lists; empty = no filter): {"session_types": ["entrenamiento", ...], "roles": ["Lateral", ...], "microcycle_days": ["MD-1", "MD", ...]}. roles match Position.role; session_types match the GPS tipo_sesion / event type; microcycle_days match the result md_label.'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='kind',
            field=models.CharField(choices=[('bound', 'Límite (umbral fijo)'), ('variation', 'Variación (% vs. ventana)'), ('zscore', 'Z-score (vs. basal móvil)'), ('pct_match', '% de la demanda de partido'), ('band', 'Banda de referencia (clínica)')], max_length=12),
        ),
    ]
