# Generated by Django 5.1.4 on 2026-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_alertrule_scope_alter_alertrule_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('threshold', 'Umbral'), ('medication', 'Medicación (WADA)'), ('training_load', 'Carga de entrenamiento'), ('molestia', 'Molestia (check-in)'), ('acwr', 'ACWR (agudo:crónico)')], max_length=20),
        ),
    ]
