# Generated by Django 5.1.4 on 2026-07-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_episode_available_at'),
        ('goals', '0014_alter_alert_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Free-text objective (required for a goal without a metric).', max_length=200),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('goal_overdue', 'Objetivo libre vencido (cierre manual)'), ('threshold', 'Umbral'), ('medication', 'Medicación (WADA)'), ('training_load', 'Carga de entrenamiento'), ('molestia', 'Molestia (check-in)'), ('acwr', 'ACWR (agudo:crónico)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='field_key',
            field=models.CharField(blank=True, default='', help_text="The key from template.config_schema['fields'][].key to evaluate.", max_length=80),
        ),
        migrations.AlterField(
            model_name='goal',
            name='operator',
            field=models.CharField(blank=True, choices=[('<=', '≤'), ('<', '<'), ('==', '='), ('>=', '≥'), ('>', '>')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='exams.examtemplate'),
        ),
    ]
