# Generated by Django 5.1.4 on 2026-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_goal_title_alter_alert_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='source_id',
            field=models.UUIDField(blank=True, help_text='UUID of the source row (Goal.id, Threshold.id, …). Null for manually-created alerts, which have no source row.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_type',
            field=models.CharField(choices=[('goal', 'Objetivo (vencimiento)'), ('goal_warning', 'Objetivo (aviso pre-vencimiento)'), ('goal_overdue', 'Objetivo libre vencido (cierre manual)'), ('threshold', 'Umbral'), ('medication', 'Medicación (WADA)'), ('training_load', 'Carga de entrenamiento'), ('molestia', 'Molestia (check-in)'), ('acwr', 'ACWR (agudo:crónico)'), ('manual', 'Manual (creada por el staff)')], max_length=20),
        ),
    ]
