# Generated by Django 5.1.4 on 2026-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_alter_alert_source_id_alter_alert_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='bound: {"upper": float?, "lower": float?}. variation: {"window": {"kind":"last_n","n":int} or {"kind":"timedelta","days":int}, "threshold_pct": float?, "threshold_units": float?, "direction": "any"|"increase"|"decrease"} — at least one threshold required. band: {} (auto-detect alert band via color heuristic) or {"trigger_labels": ["Elevado", ...]} to fire on specific bands. Optional "ranges": same shape as the field\'s reference_ranges, carrying the RULE\'s own thresholds. Es lo que hace posible tener umbrales por categoria: el club mide el mismo test con bandas distintas por edad. Sin "ranges" se usan las del campo, asi que las reglas existentes no cambian.'),
        ),
    ]
