# Generated by Django 5.1.4 on 2026-04-28 10:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_staffmembership'),
        ('exams', '0002_alter_examtemplate_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', help_text='Internal label shown in admin lists.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, the API falls back to the legacy auto-rendered grid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='core.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='core.department')),
            ],
            options={
                'ordering': ('department__name', 'category__name'),
                'unique_together': {('department', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LayoutSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Leave blank to render widgets without a section header.', max_length=120)),
                ('is_collapsible', models.BooleanField(default=True)),
                ('default_collapsed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dashboards.departmentlayout')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('column_span', models.PositiveSmallIntegerField(default=12, help_text='Width on a 12-column grid. 12 = full width, 6 = half, etc.')),
                ('display_config', models.JSONField(blank=True, default=dict, help_text='Chart-specific knobs (axis labels, units, color overrides, etc.). Optional — sensible defaults apply when empty.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.layoutsection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WidgetDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, help_text="Keys from the chosen template's config_schema, e.g. ['peso', 'masa_muscular']. Order matters — it drives column / legend order on the chart.", size=None)),
                ('aggregation', models.CharField(choices=[('latest', 'Latest result only'), ('last_n', 'Last N results'), ('all', 'All results')], default='last_n', max_length=20)),
                ('aggregation_param', models.PositiveIntegerField(default=3, help_text='N for `last_n`. Ignored for `latest` / `all`.')),
                ('label', models.CharField(blank=True, help_text='Optional override for legends / axis titles.', max_length=120)),
                ('color', models.CharField(blank=True, help_text="Optional hex color for legends / chart series, e.g. '#3b82f6'.", max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='widget_data_sources', to='exams.examtemplate')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='dashboards.widget')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
