# Generated by Django 5.1.4 on 2026-04-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='chart_height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Chart height in pixels. Leave blank to use the per-chart-type default (line ≈ 240, multi-line ≈ 280, grouped bar ≈ 220, donut ≈ 180). Recommended range: 160–600. Ignored for table-only widgets.', null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('multi_line', 'Multi-series line chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart')], max_length=40),
        ),
    ]
