# Generated by Django 5.1.4 on 2026-05-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_widget_chart_height_alter_widget_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('multi_line', 'Multi-series line chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart'), ('body_map_heatmap', 'Body map heatmap (counts per region)')], max_length=40),
        ),
    ]
