# Generated by Django 5.1.4 on 2026-05-03 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_player_status'),
        ('dashboards', '0003_alter_widget_chart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('multi_line', 'Multi-series line chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart'), ('body_map_heatmap', 'Body map heatmap (counts per region)'), ('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)')], max_length=40),
        ),
        migrations.CreateModel(
            name='TeamReportLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', help_text='Internal label shown in admin lists.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text="If unchecked, the API returns `{layout: null}` and the frontend shows the placeholder 'no report configured' state.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_layouts', to='core.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_layouts', to='core.department')),
            ],
            options={
                'ordering': ('department__name', 'category__name'),
                'unique_together': {('department', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TeamReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Leave blank to render widgets without a section header.', max_length=120)),
                ('is_collapsible', models.BooleanField(default=True)),
                ('default_collapsed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dashboards.teamreportlayout')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TeamReportWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('column_span', models.PositiveSmallIntegerField(default=12, help_text='Width on a 12-column grid. 12 = full width, 6 = half, etc.')),
                ('chart_height', models.PositiveSmallIntegerField(blank=True, help_text='Chart height in pixels. Leave blank for the per-chart-type default. For team_horizontal_comparison the default scales with roster size.', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Chart-specific data + display config. Shape depends on chart_type — see TeamReportWidget docstring + dashboards/team_aggregation.py.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.teamreportsection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
