# Generated by Django 5.1.4 on 2026-05-03 19:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_widget_chart_type_teamreportlayout_and_more'),
        ('exams', '0017_templatefield_option_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamreportwidget',
            name='config',
        ),
        migrations.AddField(
            model_name='teamreportwidget',
            name='display_config',
            field=models.JSONField(blank=True, default=dict, help_text='Chart-specific display knobs (color palette, axis labels, etc.). Optional — sensible defaults apply when empty. The actual data binding lives in the Data Sources inline below.'),
        ),
        migrations.CreateModel(
            name='TeamReportWidgetDataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, help_text="Keys from the chosen template's config_schema. For team_horizontal_comparison only the first key is used; future team widgets may consume more.", size=None)),
                ('aggregation', models.CharField(choices=[('latest', 'Latest result only'), ('last_n', 'Last N results'), ('all', 'All results')], default='last_n', max_length=20)),
                ('aggregation_param', models.PositiveIntegerField(default=3, help_text='N for `last_n`. Drives bars-per-player on horizontal comparison.')),
                ('label', models.CharField(blank=True, help_text='Optional override for legends / axis titles.', max_length=120)),
                ('color', models.CharField(blank=True, help_text="Optional hex color for legends / chart series, e.g. '#3b82f6'.", max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_widget_data_sources', to='exams.examtemplate')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='dashboards.teamreportwidget')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
