# Generated by Django 5.1.4 on 2026-05-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_remove_teamreportwidget_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentlayout',
            options={'ordering': ('department__name', 'category__name'), 'verbose_name': 'Player profile — Layout', 'verbose_name_plural': 'Player profile — Layouts'},
        ),
        migrations.AlterModelOptions(
            name='layoutsection',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Player profile — Section', 'verbose_name_plural': 'Player profile — Sections'},
        ),
        migrations.AlterModelOptions(
            name='teamreportlayout',
            options={'ordering': ('department__name', 'category__name'), 'verbose_name': 'Team report — Layout', 'verbose_name_plural': 'Team report — Layouts'},
        ),
        migrations.AlterModelOptions(
            name='teamreportsection',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Team report — Section', 'verbose_name_plural': 'Team report — Sections'},
        ),
        migrations.AlterModelOptions(
            name='teamreportwidget',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Team report — Widget', 'verbose_name_plural': 'Team report — Widgets'},
        ),
        migrations.AlterModelOptions(
            name='teamreportwidgetdatasource',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Team report — Widget data source', 'verbose_name_plural': 'Team report — Widget data sources'},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Player profile — Widget', 'verbose_name_plural': 'Player profile — Widgets'},
        ),
        migrations.AlterModelOptions(
            name='widgetdatasource',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Player profile — Widget data source', 'verbose_name_plural': 'Player profile — Widget data sources'},
        ),
    ]
