# Generated by Django 5.1.4 on 2026-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_teamreportwidget_chart_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreportwidget',
            name='chart_type',
            field=models.CharField(choices=[('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)'), ('team_roster_matrix', 'Team — roster matrix (latest values per player × metric)'), ('team_status_counts', 'Team — squad availability (ready / partial / out)'), ('team_trend_line', 'Team — trend line (team average over time)'), ('team_distribution', 'Team — distribution histogram (latest values across the roster)'), ('team_active_records', 'Team — active records (date-range filtered)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('multi_line', 'Multi-series line chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart'), ('body_map_heatmap', 'Body map heatmap (counts per region)'), ('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)'), ('team_roster_matrix', 'Team — roster matrix (latest values per player × metric)'), ('team_status_counts', 'Team — squad availability (ready / partial / out)'), ('team_trend_line', 'Team — trend line (team average over time)'), ('team_distribution', 'Team — distribution histogram (latest values across the roster)'), ('team_active_records', 'Team — active records (date-range filtered)')], max_length=40),
        ),
    ]
