# Generated by Django 5.1.4 on 2026-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_alter_teamreportwidget_chart_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamreportlayout',
            name='match_selector_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-match scoping for this layout. When enabled, the report page renders a match selector and every widget filters its data to the chosen Event. Shape: <code>{"enabled": true, "event_type": "match", "required": true, "label": "Partido", "show_recent": 10}</code>. Empty / disabled → date-window mode (current behavior).'),
        ),
    ]
