# Generated by Django 5.1.4 on 2026-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_alter_teamreportwidget_chart_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreportwidget',
            name='chart_type',
            field=models.CharField(choices=[('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)'), ('team_roster_matrix', 'Team — roster matrix (latest values per player × metric)'), ('team_status_counts', 'Team — squad availability (ready / partial / out)'), ('team_trend_line', 'Team — trend line (team average over time)'), ('team_distribution', 'Team — distribution histogram (latest values across the roster)'), ('team_active_records', 'Team — active records (date-range filtered)'), ('team_activity_coverage', 'Team — activity coverage (days since last result per template)'), ('team_leaderboard', 'Team — leaderboard (top N by a metric)'), ('team_goal_progress', 'Team — goal progress matrix (roster × goals)'), ('team_alerts', 'Team — players ranked by active alert count'), ('team_stacked_bars', 'Team — stacked bars per player (composition of N fields)'), ('team_match_summary', 'Team — match-aggregate statistics strip'), ('team_activity_log', 'Team — activity log (recent entries across the roster)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart'), ('multi_line', 'Multi-series line chart'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart'), ('body_map_heatmap', 'Body map heatmap (counts per region)'), ('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)'), ('team_roster_matrix', 'Team — roster matrix (latest values per player × metric)'), ('team_status_counts', 'Team — squad availability (ready / partial / out)'), ('team_trend_line', 'Team — trend line (team average over time)'), ('team_distribution', 'Team — distribution histogram (latest values across the roster)'), ('team_active_records', 'Team — active records (date-range filtered)'), ('team_activity_coverage', 'Team — activity coverage (days since last result per template)'), ('team_leaderboard', 'Team — leaderboard (top N by a metric)'), ('goal_card', 'Goal — current vs target cards'), ('team_goal_progress', 'Team — goal progress matrix (roster × goals)'), ('player_alerts', 'Player — active alerts list (filtered by department)'), ('team_alerts', 'Team — players ranked by active alert count'), ('team_stacked_bars', 'Team — stacked bars per player (composition of N fields)'), ('activity_log', 'Activity log (per-player timeline of recent entries)'), ('team_activity_log', 'Team — activity log (recent entries across the roster)'), ('team_match_summary', 'Team — match-aggregate statistics strip')], max_length=40),
        ),
    ]
