# Generated by Django 5.1.4 on 2026-06-17 13:57

import dashboards.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0020_alter_teamreportwidget_chart_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, default='triage', max_length=40)),
                ('data_hash', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('narrative', models.JSONField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to=dashboards.models._report_pdf_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'kind', 'data_hash'], name='dashboards__player__5cce1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'kind', 'data_hash'), name='uniq_report_snapshot_player_kind_hash')],
            },
        ),
    ]
