# Generated by Django 5.1.4 on 2026-06-17 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_playerreportsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Stable selector matching the report stage, e.g. 'triage'.", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('model', models.CharField(blank=True, help_text='Override the LLM model id; blank = settings.ANTHROPIC_MODEL.', max_length=64)),
                ('system_prompt', models.TextField(help_text='Role, tone and interpretation rules. Do NOT put the JSON output contract here — the renderer owns it.')),
                ('knowledge', models.TextField(blank=True, help_text='Editable knowledge base (markdown): club methodology, reference norms, terminology. Used as interpretation context — must NOT introduce facts about a specific player.')),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
