# Generated by Django 5.1.4 on 2026-06-18 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_seed_triage_insight_agent'),
        ('exams', '0021_episode_legacy_raw_examresult_legacy_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, max_length=80)),
                ('source', models.CharField(help_text="Where the norm comes from, e.g. 'ISAK (fútbol prof.)', 'Premier League in-season', 'Holway 2010'.", max_length=120)),
                ('sex', models.CharField(blank=True, help_text="'M'/'F' or blank (any).", max_length=1)),
                ('position', models.CharField(blank=True, help_text='Position name or blank (any).', max_length=80)),
                ('range_min', models.FloatField(blank=True, null=True)),
                ('range_max', models.FloatField(blank=True, null=True)),
                ('mean', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('percentiles', models.JSONField(blank=True, help_text='Optional percentile map, e.g. {"p5": 33.6, "p50": 65.6, "p95": 115.9}.', null=True)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_references', to='exams.examtemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'field_key', 'is_active'], name='dashboards__templat_042316_idx')],
            },
        ),
    ]
