# Generated by Django 5.1.4 on 2026-06-18 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0025_playermetricstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_on', models.DateField(db_index=True, help_text='The day this snapshot represents.')),
                ('state', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='core.player')),
            ],
            options={
                'ordering': ['captured_on'],
                'indexes': [models.Index(fields=['player', 'captured_on'], name='dashboards__player__802628_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'captured_on'), name='uniq_state_snapshot_player_day')],
            },
        ),
    ]
