# Generated by Django 5.1.4 on 2026-06-18 21:55

import dashboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_playerstatesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerreportsnapshot',
            name='docx',
            field=models.FileField(blank=True, upload_to=dashboards.models._report_pdf_path),
        ),
        migrations.AlterField(
            model_name='playerreportsnapshot',
            name='pdf',
            field=models.FileField(blank=True, upload_to=dashboards.models._report_pdf_path),
        ),
    ]
