# Generated by Django 5.1.4 on 2026-06-18 22:05

import dashboards.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0027_playerreportsnapshot_docx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hash', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('narrative', models.JSONField(blank=True, null=True)),
                ('docx', models.FileField(blank=True, upload_to=dashboards.models._team_report_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_snapshots', to='core.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_snapshots', to='core.department')),
            ],
            options={
                'indexes': [models.Index(fields=['department', 'category', 'data_hash'], name='dashboards__departm_6b6a04_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'category', 'data_hash'), name='uniq_team_report_snapshot')],
            },
        ),
    ]
