# Generated by Django 5.1.4 on 2026-06-18 22:07

import dashboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0028_teamreportsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreportsnapshot',
            name='docx',
            field=models.FileField(blank=True, max_length=255, upload_to=dashboards.models._report_pdf_path),
        ),
        migrations.AlterField(
            model_name='playerreportsnapshot',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, upload_to=dashboards.models._report_pdf_path),
        ),
        migrations.AlterField(
            model_name='teamreportsnapshot',
            name='docx',
            field=models.FileField(blank=True, max_length=255, upload_to=dashboards.models._team_report_path),
        ),
    ]
