# Generated by Django 5.1.4 on 2026-06-18 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0029_alter_playerreportsnapshot_docx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hash', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_snapshots', to='core.category')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'data_hash'], name='dashboards__categor_254035_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'data_hash'), name='uniq_briefing_snapshot')],
            },
        ),
    ]
