# Generated by Django 5.1.4 on 2026-06-19 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0030_briefingsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('deterministic', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='deterministic', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness', to='core.player')),
            ],
        ),
    ]
