# Generated by Django 5.1.4 on 2026-06-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        ('dashboards', '0032_alter_widget_chart_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamreportlayout',
            options={'ordering': ('category__name', 'scope'), 'verbose_name': 'Team report — Layout', 'verbose_name_plural': 'Team report — Layouts'},
        ),
        migrations.AlterUniqueTogether(
            name='teamreportlayout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamreportlayout',
            name='scope',
            field=models.CharField(choices=[('period', 'Período (dashboard por rango de fechas)'), ('match', 'Partido (reporte combinado)')], default='period', help_text='period = dashboard por departamento + rango de fechas (sub-ítems del menú Dashboard). match = reporte combinado del partido (cross-departamento, en Partidos, fijado al partido abierto).', max_length=10),
        ),
        migrations.AlterField(
            model_name='teamreportlayout',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department for a period dashboard. NULL for a match report (combined, cross-department).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_report_layouts', to='core.department'),
        ),
        migrations.AddConstraint(
            model_name='teamreportlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'period')), fields=('department', 'category'), name='uniq_team_period_layout'),
        ),
        migrations.AddConstraint(
            model_name='teamreportlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'match')), fields=('category',), name='uniq_team_match_layout'),
        ),
    ]
