# Generated by Django 5.1.4 on 2026-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0033_alter_teamreportlayout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetdatasource',
            name='date_shift_days',
            field=models.IntegerField(default=0, help_text="Display-only shift (in days) applied to this series' dates on cross-exam line charts. Example: CK is sampled 2 days after a match, so -2 plots each CK value on the date of the match that caused it. The stored results are untouched; tooltips still show the real sample date."),
        ),
    ]
