# Generated by Django 5.1.4 on 2026-07-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_widgetdatasource_date_shift_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='chart_height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Chart height in pixels. Leave blank to use the per-chart-type default (line ≈ 360, multi-line / cross-exam ≈ 420, grouped bar ≈ 220, donut ≈ 180). Recommended range: 160–600. Ignored for table-only widgets.', null=True),
        ),
    ]
