# Generated by Django 5.1.4 on 2026-07-21 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kinedailyentry'),
        ('dashboards', '0035_alter_widget_chart_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('text', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('data_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='core.category')),
            ],
            options={
                'verbose_name': 'Daily — resumen IA',
                'verbose_name_plural': 'Daily — resúmenes IA',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('category', 'date'), name='uniq_daily_summary')],
            },
        ),
    ]
