# Generated by Django 5.1.4 on 2026-09-23 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_category_player_comparison_perm'),
        ('dashboards', '0036_dailysummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('cards', 'Tarjetas'), ('radar', 'Radar'), ('table', 'Tabla y gráficos')], max_length=16)),
                ('metric_keys', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sections', to='core.club')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'section'), name='uniq_comparison_section_per_club')],
            },
        ),
    ]
