# Generated by Django 5.1.4 on 2026-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """Los `choices` de `Widget.chart_type`, al día con el enum.

    Sólo metadata —Django no toca el esquema por un cambio de choices— pero
    sin ella `makemigrations --check` falla y la próxima migración de verdad
    se la lleva puesta de arrastre. Corresponde a los cuatro tipos nuevos:
    `kpi_card`, `session_log`, `dual_axis_bar_line` y el `grouped_bar`
    apilable.
    """


    dependencies = [
        ('dashboards', '0037_comparisonsectionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='chart_type',
            field=models.CharField(choices=[('comparison_table', 'Comparison table (last N takes)'), ('line_with_selector', 'Line chart with field selector'), ('donut_per_result', 'Donut chart per result'), ('grouped_bar', 'Grouped bar chart (apilable)'), ('multi_line', 'Multi-series line chart'), ('training_radar', 'Radar: entrenamiento vs carga crónica'), ('reference_card', 'Reference card (current vs target)'), ('goals_list', 'Goals list'), ('cross_exam_line', 'Cross-exam line chart'), ('body_map_heatmap', 'Body map heatmap (counts per region)'), ('kpi_card', 'Tarjeta KPI (número + sparkline)'), ('session_log', 'Bitácora de sesiones (una fila por registro)'), ('dual_axis_bar_line', 'Barras + línea con eje secundario (dos métricas, dos escalas)'), ('team_horizontal_comparison', 'Team — horizontal bars (player vs. past values)'), ('team_roster_matrix', 'Team — roster matrix (latest values per player × metric)'), ('team_status_counts', 'Team — squad availability (ready / partial / out)'), ('team_trend_line', 'Team — trend line (team average over time)'), ('team_distribution', 'Team — distribution histogram (latest values across the roster)'), ('team_active_records', 'Team — active records (date-range filtered)'), ('team_activity_coverage', 'Team — activity coverage (days since last result per template)'), ('team_leaderboard', 'Team — leaderboard (top N by a metric)'), ('goal_card', 'Goal — current vs target cards'), ('team_goal_progress', 'Team — goal progress matrix (roster × goals)'), ('player_alerts', 'Player — active alerts list (filtered by department)'), ('team_alerts', 'Team — players ranked by active alert count'), ('team_stacked_bars', 'Team — stacked bars per player (composition of N fields)'), ('activity_log', 'Activity log (per-player timeline of recent entries)'), ('team_activity_log', 'Team — activity log (recent entries across the roster)'), ('team_daily_grouped_bars', 'Team — daily grouped bars (N metrics × daily buckets)'), ('team_match_summary', 'Team — match-aggregate statistics strip'), ('team_season_stats', 'Team — season stats per player (multi-match aggregate)')], max_length=40),
        ),
    ]
