# Generated by Django 5.1.4 on 2026-10-01 13:09

from django.db import migrations, models

PREVIEW_SLUG = "vista-previa-interna"


def poner_slugs(apps, schema_editor):
    """Every existing period layout gets a slug BEFORE the per-slug unique
    constraint exists. Until now there was exactly one per (department,
    category), so the generic names ("Médico", "Médico report", "Default")
    become "General" — the name a submenu shows once a second layout exists;
    a descriptive name ("Fatiga central (equipo)") is kept."""
    from django.utils.text import slugify

    Layout = apps.get_model("dashboards", "TeamReportLayout")
    for l in Layout.objects.filter(scope="period").select_related("department"):
        depto = l.department.name if l.department_id else ""
        genericos = {"", "default", depto.lower(), f"{depto} report".lower()}
        if l.name == "__chart_preview__":
            l.slug = PREVIEW_SLUG
        elif (l.name or "").strip().lower() in genericos:
            l.name, l.slug = "General", "general"
        else:
            l.slug = slugify(l.name)[:70] or "vista"
        l.save(update_fields=["name", "slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_category_player_comparison_perm'),
        ('dashboards', '0039_team_injury_widgets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamreportlayout',
            options={'ordering': ('category__name', 'scope', 'sort_order', 'created_at'), 'verbose_name': 'Team report — Layout', 'verbose_name_plural': 'Team report — Layouts'},
        ),
        migrations.RemoveConstraint(
            model_name='teamreportlayout',
            name='uniq_team_period_layout',
        ),
        migrations.AddField(
            model_name='teamreportlayout',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='URL segment: /reportes/<department>/<slug>. Unique within the (department, category); generated from the name when blank.', max_length=80),
        ),
        migrations.AddField(
            model_name='teamreportlayout',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order in the submenu; the first one opens at /reportes/<department>.'),
        ),
        migrations.AlterField(
            model_name='teamreportlayout',
            name='name',
            field=models.CharField(default='Default', help_text='Visible name. With one layout per (department, category) it only shows in admin; with several, it is the item in the Dashboard submenu (Dashboard → Médico → <name>).', max_length=120),
        ),
        migrations.RunPython(poner_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='teamreportlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'period')), fields=('department', 'category', 'slug'), name='uniq_team_period_layout_slug'),
        ),
    ]
