# Generated by Django 5.1.4 on 2026-04-30 14:19

import attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('contract', 'Contrato'), ('exam_field', 'Campo de examen'), ('exam_result', 'Resultado de examen (general)'), ('event', 'Evento')], max_length=20)),
                ('source_id', models.UUIDField(help_text='UUID of the source row (Contract.id, ExamResult.id, …).')),
                ('field_key', models.CharField(blank=True, max_length=80)),
                ('file', models.FileField(max_length=255, upload_to=attachments.models.attachment_upload_path)),
                ('filename', models.CharField(help_text='Original filename as uploaded — preserved for display.', max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='attachments_source__d8012f_idx'), models.Index(fields=['source_type', 'source_id', 'field_key'], name='attachments_source__1ed536_idx')],
            },
        ),
    ]
