# Generated by Django 5.1.4 on 2026-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='source_type',
            field=models.CharField(choices=[('contract', 'Contrato'), ('exam_field', 'Campo de examen'), ('exam_result', 'Resultado de examen (general)'), ('event', 'Evento'), ('episode_note', 'Entrada de bitácora de lesión')], max_length=20),
        ),
    ]
