# Generated by Django 5.1.4 on 2026-04-27 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.club')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('club', 'name'), ('club', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments active for this category. Must belong to the same club.', related_name='categories', to='core.department'),
        ),
    ]
