# Generated by Django 5.1.4 on 2026-04-27 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_category_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, help_text="Free-form, e.g. 'Chile'. We can promote this to an FK later.", max_length=80),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Volante Interior'", max_length=80)),
                ('abbreviation', models.CharField(help_text="e.g. 'MC'", max_length=8)),
                ('role', models.CharField(blank=True, help_text="Optional grouping shown above the name, e.g. 'Mediocampista'.", max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.club')),
            ],
            options={
                'ordering': ('sort_order', 'abbreviation'),
                'unique_together': {('club', 'abbreviation'), ('club', 'name')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.position'),
        ),
    ]
