# Generated by Django 5.1.4 on 2026-04-27 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_nationality_position_player_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('all_categories', models.BooleanField(default=False, help_text='If checked, the user has access to every category in this club, including ones added later. The categories list below is ignored.')),
                ('all_departments', models.BooleanField(default=False, help_text='If checked, the user has access to every department in this club, including ones added later. The departments list below is ignored.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text="Specific categories the user has access to. Ignored if 'All categories' is checked.", related_name='staff_memberships', to='core.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.club')),
                ('departments', models.ManyToManyField(blank=True, help_text="Specific departments the user has access to. Ignored if 'All departments' is checked.", related_name='staff_memberships', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
