# Generated by Django 5.1.4 on 2026-04-29 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('nickname', 'Nickname'), ('squad_number', 'Squad number'), ('external_id', 'External ID')], max_length=24)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('catapult', 'Catapult'), ('wimu', 'Wimu')], default='manual', help_text='Only meaningful for external IDs (Catapult, Wimu, ...).', max_length=24)),
                ('value', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.player')),
            ],
            options={
                'verbose_name': 'player alias',
                'verbose_name_plural': 'player aliases',
                'indexes': [models.Index(fields=['kind', 'source', 'value'], name='core_player_kind_6038d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'kind', 'source', 'value'), name='unique_player_alias')],
            },
        ),
    ]
