# Generated by Django 5.1.4 on 2026-04-30 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playeralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Used by clinical reference formulas (e.g. anthropometric calculations).', max_length=1),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanente'), ('loan_in', 'Préstamo (entra)'), ('loan_out', 'Préstamo (cedido)'), ('youth', 'Cantera / juvenil')], default='permanent', max_length=20)),
                ('start_date', models.DateField(help_text='Inicio Contrato')),
                ('end_date', models.DateField(help_text="Fin Contrato. UI displays as 'TT YYYY' from end_date.year.")),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=1, help_text='Porcentaje Contrato. 1.00 = club is full owner; 0.75 = co-owned.', max_digits=4)),
                ('total_gross_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total Bruto del contrato.', max_digits=15, null=True)),
                ('salary_currency', models.CharField(default='CLP', help_text='ISO currency code: CLP, USD, EUR, …', max_length=3)),
                ('fixed_bonus', models.TextField(blank=True, help_text="Bono Fijo. Ej. 'USD 60.000 por clasificar a Libertadores'.")),
                ('variable_bonus', models.TextField(blank=True, help_text="Bono Variable. Ej. 'USD 2.000 si juega 70% minutos del mes'.")),
                ('salary_increase', models.TextField(blank=True, help_text="Aumento. Ej. '15% del salario en caso de renovación'.")),
                ('purchase_option', models.TextField(blank=True, help_text="Opción de Compra. 'NO' o monto/condiciones.")),
                ('release_clause', models.TextField(blank=True, help_text="Cláusula de Salida. 'NO' o monto.")),
                ('renewal_option', models.TextField(blank=True, help_text="Opción de Renovación. 'NO', 'SI', condiciones, etc.")),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.player')),
            ],
            options={
                'ordering': ('-end_date', '-start_date'),
                'indexes': [models.Index(fields=['player', 'end_date'], name='core_contra_player__14bead_idx')],
            },
        ),
    ]
