# Generated by Django 5.1.4 on 2026-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_sex_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Latest known height in centimeters.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest known weight in kilograms.', max_digits=5, null=True),
        ),
    ]
