# Generated by Django 5.1.4 on 2026-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_current_height_cm_player_current_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('injured', 'Lesionado'), ('recovery', 'Recuperación'), ('reintegration', 'Reintegración'), ('available', 'Disponible')], db_index=True, default='available', help_text='Cached availability status — recomputed from open episodes on episodic exam templates. Worst stage across all open episodes wins.', max_length=16),
        ),
    ]
