# Generated by Django 5.1.4 on 2026-05-14 16:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_external_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del club. Aparece en la portada de los reportes PDF y como cabecera estándar. PNG con fondo transparente o JPG funcionan bien; ideal ~600px de alto.', null=True, upload_to=core.models._club_logo_upload_path),
        ),
    ]
