# Generated by Django 5.1.4 on 2026-05-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='legacy_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Source row(s) from a legacy system this contract was migrated from.'),
        ),
        migrations.AddField(
            model_name='player',
            name='legacy_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Verbatim copy of the source row(s) from a legacy system this player was migrated from. Populated by `manage.py migrate_legacy_data`; should be empty for players created directly in SLAB. Lets us re-run a migration with a refined mapping without re-querying the source.'),
        ),
        migrations.AddField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Segundo nombre. Optional — Spanish full names often use both.', max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='National ID (e.g. RUT in Chile, DNI in Argentina). Free-form to support any format.', max_length=40),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, help_text="Public URL of the player's headshot. Useful when the photo lives in an external CDN / Google Drive; for SLAB-hosted photos the standard ImageField on the admin should be used (future work).", max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('right', 'Derecho'), ('left', 'Izquierdo'), ('both', 'Ambos')], help_text='Pie hábil. Used for scouting / tactical context.', max_length=8),
        ),
        migrations.AddField(
            model_name='player',
            name='second_last_name',
            field=models.CharField(blank=True, help_text='Segundo apellido. Optional — common in Spanish naming convention.', max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position',
            field=models.ForeignKey(blank=True, help_text='A second position the player can fill, in addition to `position`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_secondary', to='core.position'),
        ),
    ]
