# Generated by Django 5.1.4 on 2026-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contract_legacy_raw_player_legacy_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeralias',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('catapult', 'Catapult'), ('wimu', 'Wimu'), ('wyscout', 'Wyscout')], default='manual', help_text='Only meaningful for external IDs (Catapult, Wimu, ...).', max_length=24),
        ),
    ]
