# Generated by Django 5.1.4 on 2026-07-05 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_wyscout_alias_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Meeting day the note belongs to.')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_notes', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Área that raised the note (Médico, Físico, Nutrición, ...). Empty = general/cross-department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_notes', to='core.department')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='core.player')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['date', 'player'], name='core_dailyn_date_9f1f12_idx')],
            },
        ),
    ]
