# Generated by Django 5.1.4 on 2026-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dailynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('injured', 'Lesionado'), ('recovery', 'Recuperación'), ('reintegration', 'Return to Train'), ('available', 'Disponible')], db_index=True, default='available', help_text='Cached availability status — recomputed from open episodes on episodic exam templates. Worst stage across all open episodes wins.', max_length=16),
        ),
    ]
