# Generated by Django 5.1.4 on 2026-07-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='kind',
            field=models.CharField(choices=[('pauta', 'Pauta del día'), ('plan', 'Plan de trabajo')], db_index=True, default='pauta', max_length=16),
        ),
    ]
