# Generated by Django 5.1.4 on 2026-07-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dailynote_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='load_config',
            field=models.JSONField(blank=True, default=dict, help_text='Load-monitoring parameters (ACWR, etc.), editable per category. Empty = system defaults (tot_dist, 7:28 moving average, target band 0.8–1.3). Shape: <code>{"acwr": {"variables": [{"field": "tot_dist", "acute_days": 7, "chronic_days": 28, "method": "moving_avg", "sweet_low": 0.8, "sweet_high": 1.3, "danger_low": 0.7, "danger_high": 1.5, "label": "Distancia total", "alert": false, "severity": "warning"}]}}</code>. method = moving_avg | ewma; add more entries to monitor several variables.'),
        ),
    ]
