# Generated by Django 5.1.4 on 2026-07-14 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_category_load_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KineDailyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Day this plan belongs to.')),
                ('clinica', models.CharField(blank=True, max_length=200)),
                ('gimnasio', models.CharField(blank=True, max_length=200)),
                ('cancha', models.CharField(blank=True, max_length=200)),
                ('objetivo', models.CharField(blank=True, max_length=300)),
                ('kinesiologo', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kine_daily_entries', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kine_daily_entries', to='core.player')),
            ],
            options={
                'ordering': ('date', 'player__last_name'),
                'indexes': [models.Index(fields=['date', 'player'], name='core_kineda_date_2bc980_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'player'), name='uniq_kine_entry_per_player_day')],
            },
        ),
    ]
