# Generated by Django 5.1.4 on 2026-07-25 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kinedailyentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCallUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('call_up', 'Convocado'), ('promotion_track', 'Proyección (listo para subir)')], default='call_up', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True, help_text="Inactive call-ups drop the player from the category's access + views (history kept).")),
                ('since', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text="Category the player is called up TO (must differ from the player's home category).", on_delete=django.db.models.deletion.CASCADE, related_name='called_up_players', to='core.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_call_ups', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_ups', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'active'], name='core_player_categor_9a1fb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'category'), name='uniq_player_callup_category')],
            },
        ),
    ]
