# Generated by Django 5.1.4 on 2026-08-22 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_playercallup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Stable key, e.g. 'sub_15', 'primera'.", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Shown to users: 'Sub 15'.", max_length=40)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Nominal age of the bracket. Empty for senior competitions.', null=True)),
                ('order', models.PositiveIntegerField(help_text='Rung on the real ladder, ascending. Consecutive by construction even where the ages skip (Sub 16 → Sub 18).', unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de competencia',
                'verbose_name_plural': 'Categorías de competencia',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='cohort_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text="Birth year of the group this team IS, for age-group teams. The durable identity: the 2012s are the 2012s in every season, while the competition they play in changes every year (see TeamSeason). Leave empty for teams that aren't an age group — first team, women's squads.", null=True),
        ),
        migrations.CreateModel(
            name='PlayerTeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True, help_text='Empty = current spell.', null=True)),
                ('reason', models.CharField(blank=True, help_text="Why the spell started: 'traspaso', 'carga inicial'…", max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='core.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_memberships', to='core.category')),
            ],
            options={
                'verbose_name': 'Pertenencia a equipo',
                'verbose_name_plural': 'Pertenencias a equipo',
                'ordering': ['player_id', '-since'],
                'indexes': [models.Index(fields=['player', 'until'], name='core_player_player__15db28_idx'), models.Index(fields=['team', 'until'], name='core_player_team_id_50be3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.PositiveIntegerField(db_index=True, help_text='Calendar year.')),
                ('external_config', models.JSONField(blank=True, default=dict, help_text='Per-season provider binding. Same shape Category used.')),
                ('derived', models.BooleanField(default=False, help_text='True when a backfill inferred this row instead of a human declaring it. Lets a correction be told apart from a guess.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_seasons', to='core.bracket')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='core.category')),
            ],
            options={
                'verbose_name': 'Temporada de equipo',
                'verbose_name_plural': 'Temporadas de equipo',
                'ordering': ['-season'],
                'constraints': [models.UniqueConstraint(fields=('team', 'season'), name='uniq_team_season')],
            },
        ),
    ]
