# Generated by Django 5.1.4 on 2026-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bracket_category_cohort_year_playerteammembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_senior',
            field=models.BooleanField(db_index=True, default=False, help_text='The club\'s first team — the squad that enters competitions with no age limit. Set exactly one per club. Code used to look for the name "Primer Equipo" to answer this, which put a club decision somewhere the club couldn\'t change it: renaming the category silently broke which squad received senior fixtures.'),
        ),
    ]
