# Generated by Django 5.1.4 on 2026-08-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_finish_dissolving_sub17'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_development', 'Puede ver los módulos Desarrollo y Crecimiento')], 'verbose_name_plural': 'categories'},
        ),
    ]
