# Generated by Django 5.1.4 on 2026-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):
    """Suma `view_player_comparison` al Meta de Category.

    Sólo declara el permiso; no se lo otorga a nadie. Quien lo necesite se lo
    asigna a mano (o por grupo) desde el admin — ver el comentario en
    `Category.Meta.permissions`.
    """


    dependencies = [
        ('core', '0026_category_view_development_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_development', 'Puede ver los módulos Desarrollo y Crecimiento'), ('view_player_comparison', 'Puede ver el comparador de jugadores entre divisiones')], 'verbose_name_plural': 'categories'},
        ),
    ]
